-- MySQL Script generated by MySQL Workbench
-- Thu Apr 30 22:24:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL,
  `uf` VARCHAR(150) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT NOT NULL,
  `nomCidad` VARCHAR(150) NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `idBairro` INT NOT NULL,
  `nomBairr` VARCHAR(150) NULL,
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idBairro`),
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEnder` INT NOT NULL,
  `tipoLogradouro` VARCHAR(150) NULL,
  `nomeLogradouro` VARCHAR(150) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(300) NULL,
  `cep` VARCHAR(9) NULL,
  `Bairro_idBairro` INT NOT NULL,
  PRIMARY KEY (`idEnder`),
  INDEX `fk_Endereco_Bairro1_idx` (`Bairro_idBairro` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`Bairro_idBairro`)
    REFERENCES `mydb`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coordenador` (
  `idCordenador` INT NOT NULL,
  `nomeCoordenador` VARCHAR(150) NULL,
  `emailCoordenador` VARCHAR(150) NULL,
  `instituiçãoCoordenador` VARCHAR(150) NULL,
  `Endereco_idEnder` INT NOT NULL,
  PRIMARY KEY (`idCordenador`),
  INDEX `fk_Coordenador_Endereco1_idx` (`Endereco_idEnder` ASC) VISIBLE,
  CONSTRAINT `fk_Coordenador_Endereco1`
    FOREIGN KEY (`Endereco_idEnder`)
    REFERENCES `mydb`.`Endereco` (`idEnder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AreaInteresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AreaInteresse` (
  `idArInt` INT NOT NULL,
  `nomeArPes` VARCHAR(150) NULL,
  PRIMARY KEY (`idArInt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pesquisa` (
  `idPesquisa` INT NOT NULL,
  `nomPesquisa` VARCHAR(150) NULL,
  `descPesquisa` VARCHAR(300) NULL,
  `dataInicio` DATETIME NULL,
  `dataFimEfetiva` DATETIME NULL,
  `dataFimPrevista` DATETIME NULL,
  `Coordenador_idCordenador` INT NOT NULL,
  `AreaPesquisa_idArPes` INT NOT NULL,
  PRIMARY KEY (`idPesquisa`),
  INDEX `fk_Pesquisa_Coordenador_idx` (`Coordenador_idCordenador` ASC) VISIBLE,
  INDEX `fk_Pesquisa_AreaPesquisa1_idx` (`AreaPesquisa_idArPes` ASC) VISIBLE,
  CONSTRAINT `fk_Pesquisa_Coordenador`
    FOREIGN KEY (`Coordenador_idCordenador`)
    REFERENCES `mydb`.`Coordenador` (`idCordenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pesquisa_AreaPesquisa1`
    FOREIGN KEY (`AreaPesquisa_idArPes`)
    REFERENCES `mydb`.`AreaInteresse` (`idArInt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacao` (
  `idPublicacao` INT NOT NULL,
  `titulo` VARCHAR(150) NULL,
  `ano` YEAR(4) NULL,
  `isbn` VARCHAR(7) NULL,
  `AreaPesquisa_idArPes` INT NOT NULL,
  PRIMARY KEY (`idPublicacao`),
  INDEX `fk_Publicacao_AreaPesquisa1_idx` (`AreaPesquisa_idArPes` ASC) VISIBLE,
  CONSTRAINT `fk_Publicacao_AreaPesquisa1`
    FOREIGN KEY (`AreaPesquisa_idArPes`)
    REFERENCES `mydb`.`AreaInteresse` (`idArInt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL,
  `nomeAutor` VARCHAR(300) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacao_has_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacao_has_Autor` (
  `Publicacao_idPublicacao` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`Publicacao_idPublicacao`, `Autor_idAutor`),
  INDEX `fk_Publicacao_has_Autor_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_Publicacao_has_Autor_Publicacao1_idx` (`Publicacao_idPublicacao` ASC) VISIBLE,
  CONSTRAINT `fk_Publicacao_has_Autor_Publicacao1`
    FOREIGN KEY (`Publicacao_idPublicacao`)
    REFERENCES `mydb`.`Publicacao` (`idPublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publicacao_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituicao` (
  `idInst` INT NOT NULL,
  `instituicao` VARCHAR(150) NULL,
  PRIMARY KEY (`idInst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grau` (
  `idGrau` INT NOT NULL,
  `grau` VARCHAR(150) NULL,
  PRIMARY KEY (`idGrau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tese` (
  `idTese` INT NOT NULL,
  `Instituicao_idInst` INT NOT NULL,
  `Grau_idGrau` INT NOT NULL,
  INDEX `fk_Tese_Instituicao1_idx` (`Instituicao_idInst` ASC) VISIBLE,
  INDEX `fk_Tese_Grau1_idx` (`Grau_idGrau` ASC) VISIBLE,
  PRIMARY KEY (`idTese`),
  CONSTRAINT `fk_Tese_Instituicao1`
    FOREIGN KEY (`Instituicao_idInst`)
    REFERENCES `mydb`.`Instituicao` (`idInst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tese_Grau1`
    FOREIGN KEY (`Grau_idGrau`)
    REFERENCES `mydb`.`Grau` (`idGrau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tese_Publicacao1`
    FOREIGN KEY (`idTese`)
    REFERENCES `mydb`.`Publicacao` (`idPublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editora` (
  `idEditora` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  PRIMARY KEY (`idEditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `idLivro` INT NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  `Editora_idEditora` INT NOT NULL,
  INDEX `fk_Livro_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  INDEX `fk_Livro_Editora1_idx` (`Editora_idEditora` ASC) VISIBLE,
  PRIMARY KEY (`idLivro`),
  CONSTRAINT `fk_Livro_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Editora1`
    FOREIGN KEY (`Editora_idEditora`)
    REFERENCES `mydb`.`Editora` (`idEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Publicacao1`
    FOREIGN KEY (`idLivro`)
    REFERENCES `mydb`.`Publicacao` (`idPublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arquivo` (
  `idArquivo` INT NOT NULL,
  `nome` VARCHAR(300) NULL,
  `caminho` VARCHAR(300) NULL,
  PRIMARY KEY (`idArquivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SoftwareTutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SoftwareTutorial` (
  `idSoftTutr` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  `descricao` VARCHAR(500) NULL,
  `responsavel` VARCHAR(150) NULL,
  `equipamento` VARCHAR(150) NULL,
  `url` VARCHAR(150) NULL,
  `Endereco_idEnder` INT NOT NULL,
  `Arquivo_idArquivo` INT NOT NULL,
  `AreaInteresse_idArInt` INT NOT NULL,
  PRIMARY KEY (`idSoftTutr`),
  INDEX `fk_SoftwareTutorial_Endereco1_idx` (`Endereco_idEnder` ASC) VISIBLE,
  INDEX `fk_SoftwareTutorial_Arquivo1_idx` (`Arquivo_idArquivo` ASC) VISIBLE,
  INDEX `fk_SoftwareTutorial_AreaInteresse1_idx` (`AreaInteresse_idArInt` ASC) VISIBLE,
  CONSTRAINT `fk_SoftwareTutorial_Endereco1`
    FOREIGN KEY (`Endereco_idEnder`)
    REFERENCES `mydb`.`Endereco` (`idEnder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SoftwareTutorial_Arquivo1`
    FOREIGN KEY (`Arquivo_idArquivo`)
    REFERENCES `mydb`.`Arquivo` (`idArquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SoftwareTutorial_AreaInteresse1`
    FOREIGN KEY (`AreaInteresse_idArInt`)
    REFERENCES `mydb`.`AreaInteresse` (`idArInt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artigo` (
  `idArtigo` INT NOT NULL,
  `nomePeriodico` VARCHAR(150) NULL,
  `volume` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtigo`),
  CONSTRAINT `fk_Artigo_Publicacao1`
    FOREIGN KEY (`idArtigo`)
    REFERENCES `mydb`.`Publicacao` (`idPublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
